/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_kako_examples_jni_Main */

#ifndef _Included_cc_kako_examples_jni_Main
#define _Included_cc_kako_examples_jni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_kako_examples_jni_Main
 * Method:    nativePrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_kako_examples_jni_Main_nativePrint
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
