/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_kako_examples_jni_NativeSampler */

#ifndef _Included_cc_kako_examples_jni_NativeSampler
#define _Included_cc_kako_examples_jni_NativeSampler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeMethodWithArguments
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeMethodWithArguments
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativePrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_kako_examples_jni_NativeSampler_nativePrint
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeString
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeBoolean
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeBooleanBoxed
 * Signature: ()Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeBooleanBoxed
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeChar
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeCharBoxed
 * Signature: ()Ljava/lang/Character;
 */
JNIEXPORT jobject JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeCharBoxed
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeInt
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeIntBoxed
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeIntBoxed
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeLong
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeLongBoxed
 * Signature: ()Ljava/lang/Long;
 */
JNIEXPORT jobject JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeLongBoxed
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeShort
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeShortBoxed
 * Signature: ()Ljava/lang/Short;
 */
JNIEXPORT jobject JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeShortBoxed
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeDouble
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeDoubleBoxed
 * Signature: ()Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeDoubleBoxed
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeFloat
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeFloatBoxed
 * Signature: ()Ljava/lang/Float;
 */
JNIEXPORT jobject JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeFloatBoxed
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeNull
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeNull
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeIntArray
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeIntArray
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeIntArray2D
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeIntArray2D
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeCharArray
 * Signature: ()[C
 */
JNIEXPORT jcharArray JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeCharArray
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeStringList
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeStringList
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeStringMap
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeStringMap
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeException
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeException
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
