/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_kako_examples_jni_NativeSampler */

#ifndef _Included_cc_kako_examples_jni_NativeSampler
#define _Included_cc_kako_examples_jni_NativeSampler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativePrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_kako_examples_jni_NativeSampler_nativePrint
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeString
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeInt
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeIntArray
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeIntArray
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeIntegerObject
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeIntegerObject
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeRotateString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeRotateString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeArraySumParallel
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeArraySumParallel
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeOpenGLTriangle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeOpenGLTriangle
  (JNIEnv *, jclass);

/*
 * Class:     cc_kako_examples_jni_NativeSampler
 * Method:    nativeRaiseException
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_kako_examples_jni_NativeSampler_nativeRaiseException
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
